// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package brew

import (
	"sync"
)

// Ensure that MoqBrewInstaller does implement BrewInstaller.
// If this is not the case, regenerate this file with mockery.
var _ BrewInstaller = &MoqBrewInstaller{}

// MoqBrewInstaller is a mock implementation of BrewInstaller.
//
//	func TestSomethingThatUsesBrewInstaller(t *testing.T) {
//
//		// make and configure a mocked BrewInstaller
//		mockedBrewInstaller := &MoqBrewInstaller{
//			InstallFunc: func() error {
//				panic("mock out the Install method")
//			},
//			IsAvailableFunc: func() (bool, error) {
//				panic("mock out the IsAvailable method")
//			},
//		}
//
//		// use mockedBrewInstaller in code that requires BrewInstaller
//		// and then make assertions.
//
//	}
type MoqBrewInstaller struct {
	// InstallFunc mocks the Install method.
	InstallFunc func() error

	// IsAvailableFunc mocks the IsAvailable method.
	IsAvailableFunc func() (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Install holds details about calls to the Install method.
		Install []struct {
		}
		// IsAvailable holds details about calls to the IsAvailable method.
		IsAvailable []struct {
		}
	}
	lockInstall     sync.RWMutex
	lockIsAvailable sync.RWMutex
}

// Install calls InstallFunc.
func (mock *MoqBrewInstaller) Install() error {
	if mock.InstallFunc == nil {
		panic("MoqBrewInstaller.InstallFunc: method is nil but BrewInstaller.Install was just called")
	}
	callInfo := struct {
	}{}
	mock.lockInstall.Lock()
	mock.calls.Install = append(mock.calls.Install, callInfo)
	mock.lockInstall.Unlock()
	return mock.InstallFunc()
}

// InstallCalls gets all the calls that were made to Install.
// Check the length with:
//
//	len(mockedBrewInstaller.InstallCalls())
func (mock *MoqBrewInstaller) InstallCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockInstall.RLock()
	calls = mock.calls.Install
	mock.lockInstall.RUnlock()
	return calls
}

// IsAvailable calls IsAvailableFunc.
func (mock *MoqBrewInstaller) IsAvailable() (bool, error) {
	if mock.IsAvailableFunc == nil {
		panic("MoqBrewInstaller.IsAvailableFunc: method is nil but BrewInstaller.IsAvailable was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsAvailable.Lock()
	mock.calls.IsAvailable = append(mock.calls.IsAvailable, callInfo)
	mock.lockIsAvailable.Unlock()
	return mock.IsAvailableFunc()
}

// IsAvailableCalls gets all the calls that were made to IsAvailable.
// Check the length with:
//
//	len(mockedBrewInstaller.IsAvailableCalls())
func (mock *MoqBrewInstaller) IsAvailableCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsAvailable.RLock()
	calls = mock.calls.IsAvailable
	mock.lockIsAvailable.RUnlock()
	return calls
}
