// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package utils

import (
	"sync"
)

// Ensure that MoqProgramExistsQuery does implement ProgramExistsQuery.
// If this is not the case, regenerate this file with mockery.
var _ ProgramExistsQuery = &MoqProgramExistsQuery{}

// MoqProgramExistsQuery is a mock implementation of ProgramExistsQuery.
//
//	func TestSomethingThatUsesProgramExistsQuery(t *testing.T) {
//
//		// make and configure a mocked ProgramExistsQuery
//		mockedProgramExistsQuery := &MoqProgramExistsQuery{
//			ProgramExistsFunc: func(program string) (bool, error) {
//				panic("mock out the ProgramExists method")
//			},
//		}
//
//		// use mockedProgramExistsQuery in code that requires ProgramExistsQuery
//		// and then make assertions.
//
//	}
type MoqProgramExistsQuery struct {
	// ProgramExistsFunc mocks the ProgramExists method.
	ProgramExistsFunc func(program string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// ProgramExists holds details about calls to the ProgramExists method.
		ProgramExists []struct {
			// Program is the program argument value.
			Program string
		}
	}
	lockProgramExists sync.RWMutex
}

// ProgramExists calls ProgramExistsFunc.
func (mock *MoqProgramExistsQuery) ProgramExists(program string) (bool, error) {
	if mock.ProgramExistsFunc == nil {
		panic("MoqProgramExistsQuery.ProgramExistsFunc: method is nil but ProgramExistsQuery.ProgramExists was just called")
	}
	callInfo := struct {
		Program string
	}{
		Program: program,
	}
	mock.lockProgramExists.Lock()
	mock.calls.ProgramExists = append(mock.calls.ProgramExists, callInfo)
	mock.lockProgramExists.Unlock()
	return mock.ProgramExistsFunc(program)
}

// ProgramExistsCalls gets all the calls that were made to ProgramExists.
// Check the length with:
//
//	len(mockedProgramExistsQuery.ProgramExistsCalls())
func (mock *MoqProgramExistsQuery) ProgramExistsCalls() []struct {
	Program string
} {
	var calls []struct {
		Program string
	}
	mock.lockProgramExists.RLock()
	calls = mock.calls.ProgramExists
	mock.lockProgramExists.RUnlock()
	return calls
}
