// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package shell

import (
	"context"
	"sync"
)

// Ensure that MoqShellChanger does implement ShellChanger.
// If this is not the case, regenerate this file with mockery.
var _ ShellChanger = &MoqShellChanger{}

// MoqShellChanger is a mock implementation of ShellChanger.
//
//	func TestSomethingThatUsesShellChanger(t *testing.T) {
//
//		// make and configure a mocked ShellChanger
//		mockedShellChanger := &MoqShellChanger{
//			GetShellPathFunc: func() (string, error) {
//				panic("mock out the GetShellPath method")
//			},
//			IsCurrentDefaultFunc: func() (bool, error) {
//				panic("mock out the IsCurrentDefault method")
//			},
//			SetAsDefaultFunc: func(ctx context.Context) error {
//				panic("mock out the SetAsDefault method")
//			},
//		}
//
//		// use mockedShellChanger in code that requires ShellChanger
//		// and then make assertions.
//
//	}
type MoqShellChanger struct {
	// GetShellPathFunc mocks the GetShellPath method.
	GetShellPathFunc func() (string, error)

	// IsCurrentDefaultFunc mocks the IsCurrentDefault method.
	IsCurrentDefaultFunc func() (bool, error)

	// SetAsDefaultFunc mocks the SetAsDefault method.
	SetAsDefaultFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// GetShellPath holds details about calls to the GetShellPath method.
		GetShellPath []struct {
		}
		// IsCurrentDefault holds details about calls to the IsCurrentDefault method.
		IsCurrentDefault []struct {
		}
		// SetAsDefault holds details about calls to the SetAsDefault method.
		SetAsDefault []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetShellPath     sync.RWMutex
	lockIsCurrentDefault sync.RWMutex
	lockSetAsDefault     sync.RWMutex
}

// GetShellPath calls GetShellPathFunc.
func (mock *MoqShellChanger) GetShellPath() (string, error) {
	if mock.GetShellPathFunc == nil {
		panic("MoqShellChanger.GetShellPathFunc: method is nil but ShellChanger.GetShellPath was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetShellPath.Lock()
	mock.calls.GetShellPath = append(mock.calls.GetShellPath, callInfo)
	mock.lockGetShellPath.Unlock()
	return mock.GetShellPathFunc()
}

// GetShellPathCalls gets all the calls that were made to GetShellPath.
// Check the length with:
//
//	len(mockedShellChanger.GetShellPathCalls())
func (mock *MoqShellChanger) GetShellPathCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetShellPath.RLock()
	calls = mock.calls.GetShellPath
	mock.lockGetShellPath.RUnlock()
	return calls
}

// IsCurrentDefault calls IsCurrentDefaultFunc.
func (mock *MoqShellChanger) IsCurrentDefault() (bool, error) {
	if mock.IsCurrentDefaultFunc == nil {
		panic("MoqShellChanger.IsCurrentDefaultFunc: method is nil but ShellChanger.IsCurrentDefault was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsCurrentDefault.Lock()
	mock.calls.IsCurrentDefault = append(mock.calls.IsCurrentDefault, callInfo)
	mock.lockIsCurrentDefault.Unlock()
	return mock.IsCurrentDefaultFunc()
}

// IsCurrentDefaultCalls gets all the calls that were made to IsCurrentDefault.
// Check the length with:
//
//	len(mockedShellChanger.IsCurrentDefaultCalls())
func (mock *MoqShellChanger) IsCurrentDefaultCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsCurrentDefault.RLock()
	calls = mock.calls.IsCurrentDefault
	mock.lockIsCurrentDefault.RUnlock()
	return calls
}

// SetAsDefault calls SetAsDefaultFunc.
func (mock *MoqShellChanger) SetAsDefault(ctx context.Context) error {
	if mock.SetAsDefaultFunc == nil {
		panic("MoqShellChanger.SetAsDefaultFunc: method is nil but ShellChanger.SetAsDefault was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSetAsDefault.Lock()
	mock.calls.SetAsDefault = append(mock.calls.SetAsDefault, callInfo)
	mock.lockSetAsDefault.Unlock()
	return mock.SetAsDefaultFunc(ctx)
}

// SetAsDefaultCalls gets all the calls that were made to SetAsDefault.
// Check the length with:
//
//	len(mockedShellChanger.SetAsDefaultCalls())
func (mock *MoqShellChanger) SetAsDefaultCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSetAsDefault.RLock()
	calls = mock.calls.SetAsDefault
	mock.lockSetAsDefault.RUnlock()
	return calls
}
