// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package shell

import (
	"sync"
)

// Ensure that MoqShellResolver does implement ShellResolver.
// If this is not the case, regenerate this file with mockery.
var _ ShellResolver = &MoqShellResolver{}

// MoqShellResolver is a mock implementation of ShellResolver.
//
//	func TestSomethingThatUsesShellResolver(t *testing.T) {
//
//		// make and configure a mocked ShellResolver
//		mockedShellResolver := &MoqShellResolver{
//			GetShellPathFunc: func() (string, error) {
//				panic("mock out the GetShellPath method")
//			},
//			IsAvailableFunc: func() (bool, error) {
//				panic("mock out the IsAvailable method")
//			},
//		}
//
//		// use mockedShellResolver in code that requires ShellResolver
//		// and then make assertions.
//
//	}
type MoqShellResolver struct {
	// GetShellPathFunc mocks the GetShellPath method.
	GetShellPathFunc func() (string, error)

	// IsAvailableFunc mocks the IsAvailable method.
	IsAvailableFunc func() (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetShellPath holds details about calls to the GetShellPath method.
		GetShellPath []struct {
		}
		// IsAvailable holds details about calls to the IsAvailable method.
		IsAvailable []struct {
		}
	}
	lockGetShellPath sync.RWMutex
	lockIsAvailable  sync.RWMutex
}

// GetShellPath calls GetShellPathFunc.
func (mock *MoqShellResolver) GetShellPath() (string, error) {
	if mock.GetShellPathFunc == nil {
		panic("MoqShellResolver.GetShellPathFunc: method is nil but ShellResolver.GetShellPath was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetShellPath.Lock()
	mock.calls.GetShellPath = append(mock.calls.GetShellPath, callInfo)
	mock.lockGetShellPath.Unlock()
	return mock.GetShellPathFunc()
}

// GetShellPathCalls gets all the calls that were made to GetShellPath.
// Check the length with:
//
//	len(mockedShellResolver.GetShellPathCalls())
func (mock *MoqShellResolver) GetShellPathCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetShellPath.RLock()
	calls = mock.calls.GetShellPath
	mock.lockGetShellPath.RUnlock()
	return calls
}

// IsAvailable calls IsAvailableFunc.
func (mock *MoqShellResolver) IsAvailable() (bool, error) {
	if mock.IsAvailableFunc == nil {
		panic("MoqShellResolver.IsAvailableFunc: method is nil but ShellResolver.IsAvailable was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsAvailable.Lock()
	mock.calls.IsAvailable = append(mock.calls.IsAvailable, callInfo)
	mock.lockIsAvailable.Unlock()
	return mock.IsAvailableFunc()
}

// IsAvailableCalls gets all the calls that were made to IsAvailable.
// Check the length with:
//
//	len(mockedShellResolver.IsAvailableCalls())
func (mock *MoqShellResolver) IsAvailableCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsAvailable.RLock()
	calls = mock.calls.IsAvailable
	mock.lockIsAvailable.RUnlock()
	return calls
}
