// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package osmanager

import (
	"sync"
)

// Ensure that MoqEtcShellsManager does implement EtcShellsManager.
// If this is not the case, regenerate this file with mockery.
var _ EtcShellsManager = &MoqEtcShellsManager{}

// MoqEtcShellsManager is a mock implementation of EtcShellsManager.
//
//	func TestSomethingThatUsesEtcShellsManager(t *testing.T) {
//
//		// make and configure a mocked EtcShellsManager
//		mockedEtcShellsManager := &MoqEtcShellsManager{
//			EnsureShellInEtcShellsFunc: func(shellPath string) error {
//				panic("mock out the EnsureShellInEtcShells method")
//			},
//		}
//
//		// use mockedEtcShellsManager in code that requires EtcShellsManager
//		// and then make assertions.
//
//	}
type MoqEtcShellsManager struct {
	// EnsureShellInEtcShellsFunc mocks the EnsureShellInEtcShells method.
	EnsureShellInEtcShellsFunc func(shellPath string) error

	// calls tracks calls to the methods.
	calls struct {
		// EnsureShellInEtcShells holds details about calls to the EnsureShellInEtcShells method.
		EnsureShellInEtcShells []struct {
			// ShellPath is the shellPath argument value.
			ShellPath string
		}
	}
	lockEnsureShellInEtcShells sync.RWMutex
}

// EnsureShellInEtcShells calls EnsureShellInEtcShellsFunc.
func (mock *MoqEtcShellsManager) EnsureShellInEtcShells(shellPath string) error {
	if mock.EnsureShellInEtcShellsFunc == nil {
		panic("MoqEtcShellsManager.EnsureShellInEtcShellsFunc: method is nil but EtcShellsManager.EnsureShellInEtcShells was just called")
	}
	callInfo := struct {
		ShellPath string
	}{
		ShellPath: shellPath,
	}
	mock.lockEnsureShellInEtcShells.Lock()
	mock.calls.EnsureShellInEtcShells = append(mock.calls.EnsureShellInEtcShells, callInfo)
	mock.lockEnsureShellInEtcShells.Unlock()
	return mock.EnsureShellInEtcShellsFunc(shellPath)
}

// EnsureShellInEtcShellsCalls gets all the calls that were made to EnsureShellInEtcShells.
// Check the length with:
//
//	len(mockedEtcShellsManager.EnsureShellInEtcShellsCalls())
func (mock *MoqEtcShellsManager) EnsureShellInEtcShellsCalls() []struct {
	ShellPath string
} {
	var calls []struct {
		ShellPath string
	}
	mock.lockEnsureShellInEtcShells.RLock()
	calls = mock.calls.EnsureShellInEtcShells
	mock.lockEnsureShellInEtcShells.RUnlock()
	return calls
}
