// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package osmanager

import (
	"os"
	"sync"
)

// Ensure that MoqFilePermissionManager does implement FilePermissionManager.
// If this is not the case, regenerate this file with mockery.
var _ FilePermissionManager = &MoqFilePermissionManager{}

// MoqFilePermissionManager is a mock implementation of FilePermissionManager.
//
//	func TestSomethingThatUsesFilePermissionManager(t *testing.T) {
//
//		// make and configure a mocked FilePermissionManager
//		mockedFilePermissionManager := &MoqFilePermissionManager{
//			GetFileOwnerFunc: func(path string) (string, error) {
//				panic("mock out the GetFileOwner method")
//			},
//			SetOwnershipFunc: func(path string, username string) error {
//				panic("mock out the SetOwnership method")
//			},
//			SetPermissionsFunc: func(path string, mode os.FileMode) error {
//				panic("mock out the SetPermissions method")
//			},
//		}
//
//		// use mockedFilePermissionManager in code that requires FilePermissionManager
//		// and then make assertions.
//
//	}
type MoqFilePermissionManager struct {
	// GetFileOwnerFunc mocks the GetFileOwner method.
	GetFileOwnerFunc func(path string) (string, error)

	// SetOwnershipFunc mocks the SetOwnership method.
	SetOwnershipFunc func(path string, username string) error

	// SetPermissionsFunc mocks the SetPermissions method.
	SetPermissionsFunc func(path string, mode os.FileMode) error

	// calls tracks calls to the methods.
	calls struct {
		// GetFileOwner holds details about calls to the GetFileOwner method.
		GetFileOwner []struct {
			// Path is the path argument value.
			Path string
		}
		// SetOwnership holds details about calls to the SetOwnership method.
		SetOwnership []struct {
			// Path is the path argument value.
			Path string
			// Username is the username argument value.
			Username string
		}
		// SetPermissions holds details about calls to the SetPermissions method.
		SetPermissions []struct {
			// Path is the path argument value.
			Path string
			// Mode is the mode argument value.
			Mode os.FileMode
		}
	}
	lockGetFileOwner   sync.RWMutex
	lockSetOwnership   sync.RWMutex
	lockSetPermissions sync.RWMutex
}

// GetFileOwner calls GetFileOwnerFunc.
func (mock *MoqFilePermissionManager) GetFileOwner(path string) (string, error) {
	if mock.GetFileOwnerFunc == nil {
		panic("MoqFilePermissionManager.GetFileOwnerFunc: method is nil but FilePermissionManager.GetFileOwner was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockGetFileOwner.Lock()
	mock.calls.GetFileOwner = append(mock.calls.GetFileOwner, callInfo)
	mock.lockGetFileOwner.Unlock()
	return mock.GetFileOwnerFunc(path)
}

// GetFileOwnerCalls gets all the calls that were made to GetFileOwner.
// Check the length with:
//
//	len(mockedFilePermissionManager.GetFileOwnerCalls())
func (mock *MoqFilePermissionManager) GetFileOwnerCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockGetFileOwner.RLock()
	calls = mock.calls.GetFileOwner
	mock.lockGetFileOwner.RUnlock()
	return calls
}

// SetOwnership calls SetOwnershipFunc.
func (mock *MoqFilePermissionManager) SetOwnership(path string, username string) error {
	if mock.SetOwnershipFunc == nil {
		panic("MoqFilePermissionManager.SetOwnershipFunc: method is nil but FilePermissionManager.SetOwnership was just called")
	}
	callInfo := struct {
		Path     string
		Username string
	}{
		Path:     path,
		Username: username,
	}
	mock.lockSetOwnership.Lock()
	mock.calls.SetOwnership = append(mock.calls.SetOwnership, callInfo)
	mock.lockSetOwnership.Unlock()
	return mock.SetOwnershipFunc(path, username)
}

// SetOwnershipCalls gets all the calls that were made to SetOwnership.
// Check the length with:
//
//	len(mockedFilePermissionManager.SetOwnershipCalls())
func (mock *MoqFilePermissionManager) SetOwnershipCalls() []struct {
	Path     string
	Username string
} {
	var calls []struct {
		Path     string
		Username string
	}
	mock.lockSetOwnership.RLock()
	calls = mock.calls.SetOwnership
	mock.lockSetOwnership.RUnlock()
	return calls
}

// SetPermissions calls SetPermissionsFunc.
func (mock *MoqFilePermissionManager) SetPermissions(path string, mode os.FileMode) error {
	if mock.SetPermissionsFunc == nil {
		panic("MoqFilePermissionManager.SetPermissionsFunc: method is nil but FilePermissionManager.SetPermissions was just called")
	}
	callInfo := struct {
		Path string
		Mode os.FileMode
	}{
		Path: path,
		Mode: mode,
	}
	mock.lockSetPermissions.Lock()
	mock.calls.SetPermissions = append(mock.calls.SetPermissions, callInfo)
	mock.lockSetPermissions.Unlock()
	return mock.SetPermissionsFunc(path, mode)
}

// SetPermissionsCalls gets all the calls that were made to SetPermissions.
// Check the length with:
//
//	len(mockedFilePermissionManager.SetPermissionsCalls())
func (mock *MoqFilePermissionManager) SetPermissionsCalls() []struct {
	Path string
	Mode os.FileMode
} {
	var calls []struct {
		Path string
		Mode os.FileMode
	}
	mock.lockSetPermissions.RLock()
	calls = mock.calls.SetPermissions
	mock.lockSetPermissions.RUnlock()
	return calls
}
