version: 2

project_name: dotfiles-installer

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: dotfiles_installer
    dir: "."
    main: "."
    binary: dotfiles-installer
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: amd64

archives:
  - id: dotfiles_installer
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

release:
  # Customize the release notes
  header: |
    ## Dotfiles Installer {{.Tag}}

    This release contains prebuilt binaries for the dotfiles installer.

    ### Quick Install

    **macOS (Apple Silicon):**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/MrPointer/dotfiles/main/get.sh | bash -s -- --version {{.Tag}}
    ```

    **Or download manually:**
    ```bash
    curl -L -o dotfiles-installer.tar.gz https://github.com/MrPointer/dotfiles/releases/download/{{.Tag}}/dotfiles-installer-{{.Version}}-darwin-arm64.tar.gz
    tar -xzf dotfiles-installer.tar.gz
    chmod +x dotfiles-installer
    ```



    **Linux (x86_64):**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/MrPointer/dotfiles/main/get.sh | bash -s -- --version {{.Tag}}
    ```

    **Linux (ARM64):**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/MrPointer/dotfiles/main/get.sh | bash -s -- --version {{.Tag}}
    ```

    **Or download manually:**
    ```bash
    # Linux x86_64
    curl -L -o dotfiles-installer.tar.gz https://github.com/MrPointer/dotfiles/releases/download/{{.Tag}}/dotfiles-installer-{{.Version}}-linux-x86_64.tar.gz
    tar -xzf dotfiles-installer.tar.gz && chmod +x dotfiles-installer

    # Linux ARM64
    curl -L -o dotfiles-installer.tar.gz https://github.com/MrPointer/dotfiles/releases/download/{{.Tag}}/dotfiles-installer-{{.Version}}-linux-arm64.tar.gz
    tar -xzf dotfiles-installer.tar.gz && chmod +x dotfiles-installer
    ```

  footer: |
    ### One-Command Setup

    For immediate dotfiles installation:
    ```bash
    curl -fsSL https://raw.githubusercontent.com/MrPointer/dotfiles/main/get.sh | bash -s -- --run --version {{.Tag}}
    ```

    ### Verification

    All binaries are signed with cosign and checksums are provided in `checksums.txt`.

    **Full Changelog**: https://github.com/MrPointer/dotfiles/compare/{{.PreviousTag}}...{{.Tag}}

  # Don't create a release for pre-release tags
  prerelease: auto

  # Make the release a draft initially so you can review it
  draft: false

  # Replace existing release if it exists (useful for testing)
  replace_existing_draft: true

  # Include release notes from git log
  disable: false

  # Name template for the release
  name_template: "{{.ProjectName}} {{.Version}}"

sboms:
  - id: dotfiles_installer
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version }}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: checksums.txt
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # We'll handle changelogs manually or through GitHub's release drafter
  disable: true

# Sign the binaries and archives
signs:
  - cmd: cosign
    args:
      - sign-blob
      - --oidc-issuer=https://token.actions.githubusercontent.com
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - ${artifact}
    artifacts: binary
    output: true
