all: true
dir: "{{.InterfaceDir}}"
filename: "{{.InterfaceName}}_mock.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "Moq{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: true
require-template-schema-exists: true
template: matryer
template-schema: "{{.Template}}.schema.json"
packages:
  github.com/MrPointer/dotfiles/installer:
    config:
      all: true
